# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-25 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizacion', models.DateTimeField(verbose_name='Reserva')),
                ('contacto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Contacto')),
                ('mesa', models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.Mesa')),
            ],
        ),
    ]
